spring:
  thymeleaf:
    cache: false
    content-type: text/html
    enabled: true
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&tinyInt1isBit=false&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 1.0
mybatis:
  type-aliases-package: com.sym.miaosha.domain
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    com.sym.miaoshaodemo.dao : debug
